### ISSUE TITLE
jsoncpp(1) and Fedora 29

### ISSUE THREAD

**Issue by freemin7** [blackhole89/notekit#1]
I tried to run the binary on Fedora.
Currently i am missing the libjsoncpp.so.1 shared library which does not exist as libjsoncpp.so.1 in Fedora. I followed the work around: https://github.com/google/flutter-desktop-embedding/issues/227

After installing all jsoncpp related packages (other than mingw packages) the following files were added.
`/usr/lib64/cmake/jsoncpp
/usr/lib64/cmake/jsoncpp/jsoncppConfig-release.cmake
/usr/lib64/cmake/jsoncpp/jsoncppConfig.cmake
/usr/lib64/libjsoncpp.so
/usr/lib64/pkgconfig/jsoncpp.pc
/usr/lib64/libjsoncpp.so.19
/usr/lib64/libjsoncpp.so.1.8.4
/usr/share/licenses/jsoncpp
/usr/share/doc/jsoncpp
/usr/share/doc/jsoncpp/html/jsoncpp_8dox.html
`
The version jsoncpp Fedora 29 provides is:

`Name         : jsoncpp
Version      : 1.8.4
Release      : 5.fc29
Architecture : x86_64
Size         : 239 k
Quelle       : jsoncpp-1.8.4-5.fc29.src.rpm
Repository   : @System
Aus Paketque : fedora
Summary      : JSON library implemented in C++
URL          : https://github.com/open-source-parsers/jsoncpp
Lizenz       : Public Domain or MIT
Description  : jsoncpp is an implementation of a JSON (http://json.org) reader
             : and writer in C++. JSON (JavaScript Object Notation) is a
             : lightweight data-interchange format. It is easy for humans to
             : read and write. It is easy for machines to parse and generate.`

**Comment by blackhole89** [comment]
I don't know if the ABI changed between 1.7.3 (the version I linked against) and 1.8.4, but if not, it might work to create a symlink (i.e. `ln -s libjsoncpp.so.1.8.4 libjsoncpp.so.1`) in your `/usr/lib64` or notekit's own directory to force it to use the version you managed to install. If not, you would probably have to build from source (which should not be that painful, assuming you can find development packages for the dependencies).
