### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by phdoerfler** [blackhole89/notekit#102]
Thanks for the consideration!

**Comment by sp1ritCS** [comment]
MacOS is supported an with homebrew already. See the `Apple/` directory.
If you want to compile it from source you'll need to apply `llvm.patch` located in it, as it removes a few g++ specific quirks. 

As you can read in that `INSTALL.OSX.md` document in the same dir, I've setup a homebrew tap myself containing clatexmath and NoteKit.
However, as Homebrew is mostly made for non-graphical software, getting OSX to recognize a formula as an "Application" is not an intended usecase. Instead Homebrew uses "Casks" to manage graphical OS X Applications. However we'd need to build an app image, that ships all libraries it needs. There is [gtk-mac-bundler](https://gitlab.gnome.org/GNOME/gtk-mac-bundler), which seems to provide this, but it only works with a gtk build by jhbuild and doesn't work with homebrew's gtk build as it doesn't follow symlinks correctly and I don't have time to setup a test system for that (and implement some kind of ci runner that does this).
You're welcome to do so if you want to.

**Comment by sp1ritCS** [comment]
requesting close
