### ISSUE TITLE
[feature request] server request

### ISSUE THREAD

**Issue by starsareintherose** [blackhole89/notekit#109]
Can I host it on my server and then sync local note with server

**Comment by sp1ritCS** [comment]
why not use git?

**Comment by starsareintherose** [comment]
maybe just because other note app also support server

**Comment by sp1ritCS** [comment]
> maybe just because other note app also support server

well, NoteKit just saves notes whereever you set it's base directory to. If you want to save it on your server, just set the notedir location to whatever directory is mounted with samba, curlftpfs, etc.. or synced by whatever sync client (i.e. Nextcloud) you use. Alternatively you can make the notedir a git repo and use it as VCS to track note changes. Obv. you need to add, commit & push each time, and gits merge conflict solver isn't the best for notes, but your notes are under vcs and synced.
Doings a sync service internal to Notekit (with something like CRDTs) seems unfeasable.
