### ISSUE TITLE
chinese path photo can not be read

### ISSUE THREAD

**Issue by starsareintherose** [blackhole89/notekit#115]
```
![](%E5%8F%8C%E7%B3%BB%E7%BB%9F/v2-38148ef5c0208bc86efaf56ef08)
```
can not preview the photo, only I need to change `%E5%8F%8C%E7%B3%BB%E7%BB%9F` to `双系统`, I can preview it.

**Comment by blackhole89** [comment]
I believe we may not currently urldecode image paths. Does the standard stipulate that we should? It probably wouldn't be too difficult.

**Comment by starsareintherose** [comment]
okay, I takes too much time to convert it, I think maybe other Asian users would face this problem.

**Comment by blackhole89** [comment]
Hm. I do recognise that it may be a problem, but I'm not sure what's the best tool to use. glib added support for URI parsing in 2.66, but that would bump up our dependency version by quite a bit. 

I'll try and see if I can implement something by hand.
