### ISSUE TITLE
MacOS brew install results in error

### ISSUE THREAD

**Issue by Gys** [blackhole89/notekit#116]
Hello

I am on MacOS 12.0.1, MacBook Pro 2018, latest xcode, latest xcode commandline tools.

From: https://github.com/blackhole89/notekit/blob/master/Apple/INSTALL.OSX.md
I executed ` brew install --HEAD sp1ritCS/tap/notekit`

That results in the following messages:

        ...
        ==> Installing notekit from sp1ritcs/tap
        ==> Patching
        ==> Applying Apple/llvm.patch
        patching file main.cpp
        patching file meson.build
        ==> meson --prefix=/usr/local/Cellar/notekit/HEAD-6d6278b --libdir=/usr/local/Cellar/notekit/HEAD-6d6278b/lib --buildtype=release --wrap-mode=nofallback ..
        ==> ninja -v
        Last 15 lines from /Users/XXXX/Library/Logs/Homebrew/notekit/02.ninja:
                                                      ~~    ^
        ../notebook.cpp:1195:70: warning: unused parameter 'content_buffer' [-Wunused-parameter]
        guint8* CNotebook::on_serialize(const Glib::RefPtr<Gtk::TextBuffer>& content_buffer, const Gtk::TextBuffer::iterator& start, const Gtk::TextBuffer::iterator& end, gsize& length, bool render_images)
                                                                             ^
        ../notebook.cpp:1223:157: warning: unused parameter 'create_tags' [-Wunused-parameter]
        bool CNotebook::on_deserialize(const Glib::RefPtr<Gtk::TextBuffer>& content_buffer, Gtk::TextBuffer::iterator& iter, const guint8* data, gsize length, bool create_tags)
                                                                                                                                                                    ^
        ../notebook.cpp:1229:11: warning: comparison of integers of different signs: 'int' and 'std::basic_string<char>::size_type' (aka 'unsigned long') [-Wsign-compare]
                while(pos!=str.length()) {
                      ~~~^ ~~~~~~~~~~~~
        ../notebook.cpp:1232:10: warning: comparison of integers of different signs: 'int' and 'const typename basic_string<char, char_traits<char>, allocator<char>>::size_type' (aka 'const unsigned long') [-Wsign-compare]
                                if(pos==std::string::npos) pos=str.length();
                                   ~~~^ ~~~~~~~~~~~~~~~~~
        52 warnings generated.
        ninja: build stopped: subcommand failed.

**Comment by sp1ritCS** [comment]
hmm, it at least used to work inside githubs osx vms (afaik OSX Catalina).

could you send me the whole log from the ninja output, the last 15 lines are just warnings not any actual error.

**Comment by Gys** [comment]
Thank you for the quick reply!

I attached the complete log: [02.ninja.txt](https://github.com/blackhole89/notekit/files/7786203/02.ninja.txt)

This seems to be the problem:

        ../mainwindow.cpp:17:2: error: no member named 'setlocale' in namespace 'std'; did you mean simply 'setlocale'?
                std::setlocale(LC_NUMERIC, "C"); // workaround for old jsoncpp on German (decimal comma) systems
                ^~~~~~~~~~~~~~
                setlocale
        /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/locale.h:53:8: note: 'setlocale' declared here
        char            *setlocale(int, const char *);
                         ^

**Comment by sp1ritCS** [comment]
> This seems to be the problem

yes, that is correct. Although I have no idea why this is the case on your machine, given that I've just rebuilt the homebrow bottle on github's infrastructure and it worked.

I also fail to find any C++ STD documentation from Apple, but it seems like that this isn't the first time something like this happened (see: https://github.com/jpcre2/jpcre2/issues/21 [but doesn't the BSD distros also ship glibc & libstdc++ from GNU])

nonetheless, I think we can also just call the C function (@blackhole89) which seems to work on OSX.

I don't know if it works, but you could try to run brew with -d and when it throws the error it'll try to set you into a debug interpreter from where you can get into shell. it that works you could try to just remove the std:: infront of the setlocale in mainwindow.cpp ln. 17, then go back and continue the build.

**Comment by Gys** [comment]
I can get into shell and edit mainwindow.cpp. But how can I go back and continue the build? On shell exit I return to the menu (1. raise, 2. ignore, 3. backtrace, 4. irb, 5. shell). I cannot figure how to continue the build - it seems all options stop it. Sorry, I am not very familiar with brew nor ruby :-(

**Comment by sp1ritCS** [comment]
> Sorry, I am not very familiar with brew nor ruby :-(

well, me neither 😕


but we discovered that it actually breaks the ci builds too, it's just that the ci helper script acknowledges the error but it still lets the build pass for some reason 🤔

apparently just removing the std:: doesn't actually fix the bug, as it then doesn't do anything on c++ methods which are used by jsoncpp.

i'm currently discussing on matrix/discord with @blackhole89 on how to proceed. I guess you could just drop the --HEAD from your invocation for now. There you'll get notekit as it was on May 2021, so a few features are missing (most importantly support for pasting images). Once it's fixed I'll push an update that you can just update too with brew :)

**Comment by Gys** [comment]
Installing without `--HEAD` works perfectly!

Looking forward to working with images as well at some point :-)

**Comment by blackhole89** [comment]
If you are on a system whose locale is not German or similar (in particular, you have a decimal dot (`'.'`, as in `3.1415`) rather than a decimal comma (`','`, as in `3,1415`)), then you can also just comment out the line with setlocale (prefix `//` to it), which should enable you to run HEAD without a hitch.
