### ISSUE TITLE
Links are not clickable

### ISSUE THREAD

**Issue by Torkin1** [blackhole89/notekit#119]
Here on github, if I write a [link](https://genrandom.com/cats/), only the text in square brackets is displayed, and if I click on it the link is opened in browser. It would be nice if the same behaviour is implemented in Notekit.
Right now, links are displayed in the following way, and they are not clickable. I was thinking about an implementation similar to what you already have done with latex, with the full formula displayed when the mouse hovers over it.
![immagine](https://user-images.githubusercontent.com/32265040/151660156-62c8c370-8b99-401b-acbe-f2304c76a425.png)

**Comment by sp1ritCS** [comment]
You can try building my master branch (https://github.com/sp1ritCS/notekit)

I have implemented links (and big "link button" if there is enough whitespace) there:
![Screenshot from 2022-01-29 19-38-19](https://user-images.githubusercontent.com/31540351/151673312-f8a090d4-9637-4717-8c24-893a48e4d45c.png)

No idea if @blackhole89 is wanting to merge the backported changes I made at some point, but the link widget is in there too.

**Comment by blackhole89** [comment]
Fixed in latest version.
