### ISSUE TITLE
No way to add pictures from files.

### ISSUE THREAD

**Issue by freemin7** [blackhole89/notekit#12]
When a picture is added by drag and drop the file path is written instead.

**Comment by blackhole89** [comment]
There is currently no support for pictures (actual pictures, not the vector drawings creaed by the program). This, LaTeX rendering and some Markdown feature have a shared dependency on a pretty big block of work to integrate the syntax highlighter with custom widgets, so runs of text can be rendered in other ways than as text with some highlighting applied.

**Comment by loughnane** [comment]
Just bumping this as it is something I'd love to see.

**Comment by blackhole89** [comment]
There is a newer discussion of this issue in #46 where I talk about the main holdup (architectural decisions about how to go about "bundling" the required images with a document) for this. Closing this ticket to unify discussion.
