### ISSUE TITLE
deb dependency problems on Debian 11 bullseye

### ISSUE THREAD

**Issue by hex-m** [blackhole89/notekit#122]
```
$ sudo dpkg -i notekit_0.2_amd64.deb 
(Reading database ... 468922 files and directories currently installed.)
Preparing to unpack notekit_0.2_amd64.deb ...
Unpacking notekit (0.2) over (0.2) ...
dpkg: dependency problems prevent configuration of notekit:
 notekit depends on libgtksourceviewmm-3.0-0v5 (>= 3.18.0); however:
  Package libgtksourceviewmm-3.0-0v5 is not installed.
 notekit depends on libtinyxml2-6 (>= 5.0.0) | libtinyxml2-6a (>= 5.0.0); however:
  Package libtinyxml2-6 is not installed.
  Package libtinyxml2-6a is not installed.

dpkg: error processing package notekit (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 notekit
```

`libtinyxml2` was installed already:
```
libtinyxml2-8/stable,now 8.0.0+dfsg-2 amd64 [installed,automatic]
  C++ XML parsing library

libtinyxml2.6.2v5/stable,now 2.6.2-4 amd64 [installed,automatic]
  C++ XML parsing library
```

After manually installing `libgtksourceviewmm-3.0-0v5` the first of the two problems disappeared.

**Comment by sp1ritCS** [comment]
Yeah, the deb package is built (afaik) for xUbuntu 18.04 (with quite a few workarrounds to keep it building on such an old OS)

You can try the [OBS built NoteKit](https://build.opensuse.org/package/show/home:sp1rit:testing:notekit/notekit) for Debian 11, that should work without dependency issues with
- clatexmath: https://download.opensuse.org/repositories/home:/sp1rit:/notekit/Debian_11/amd64/libclatexmath0_0.0.1.310.5ed4331-1_amd64.deb
- notekit: https://opi-proxy.opensuse.org/?obs_api_link=https://api.opensuse.org/build/home:sp1rit:testing:notekit/Debian_11/x86_64/notekit/notekit_1646845407.57d7253-1_amd64.deb&obs_instance=openSUSE

**Comment by hex-m** [comment]
Thank you!
