### ISSUE TITLE
Better syntax highlight

### ISSUE THREAD

**Issue by psydvl** [blackhole89/notekit#127]
1) I'd like to see Markdown code block even if this language not supported by my system:
For example, GitHub trying to do this:
````
``` example
blablabla
```
````
``` example
blablabla
```

2) Allow spaces between \`\`\` and language word and some text after
For example, all next code blocks will be broken, except first
````
```diff
-a = input()
+b = input()
```
``` diff
-a = input()
+b = input()
```

```diff python
-a = input()
+b = input()
```
````

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/43755002/180015804-5f78bf02-fd4e-4cc3-bf60-beff4b00cc5e.png)

</details>

**Comment by blackhole89** [comment]
I believe this should be more or less done as of commit f0d078195. Thanks for the PR!
