### ISSUE TITLE
If file is deleted since NoteKit is opened and is attempted to be opened no feedback is given

### ISSUE THREAD

**Issue by freemin7** [blackhole89/notekit#13]
1. Create a file (a) with content and save it
2. Switch to another file (b)
3. Delete (a) by external means
4. Try to select (a)

Expected behavior:
Feedback that this file (a) does not exists and removal from file list or recreation of this file (a)

Current behavior:
No visual indication print in to StdOut instead:
what  : Fehler beim Öffnen der Datei »/home/joto/Software/notekit-20190907/notesbase/(a).md«: No such file or directory

One might also consider refreshing the file overview sometimes

**Comment by blackhole89** [comment]
It should now give indication, but still not update the folder tree. (You can delete files and folders from inside notekit by using the rightclick context menu.)
