### ISSUE TITLE
Blockquotes not follows theme change

### ISSUE THREAD

**Issue by psydvl** [blackhole89/notekit#132]
1. Switch your system theme from light to dark or vice versa
2. Mostly text will change it's color, but, at least, blockquotes - not

To check:
```
Hello, world
> Hello, world
```

![image](https://user-images.githubusercontent.com/43755002/189263924-9f795d8f-f213-4ed4-8c7a-1132800f5dc6.png)
![image](https://user-images.githubusercontent.com/43755002/189263971-10c2e945-61e2-478c-8c56-3ed053be0271.png)

**Comment by blackhole89** [comment]
Right now, parts of the internal settings are not recomputed if the theme is changed while Notekit is running. Blockquote text should get an appropriately bright colour if you start the program up with a dark background/light foreground theme already set.

It seems like we might have to do something along the lines of the solutions discussed [here](https://stackoverflow.com/questions/62613139/gtk3-listen-to-theme-changes) to deal with that.
