### ISSUE TITLE
Cannot add PPA: ''This PPA does not support jammy''.

### ISSUE THREAD

**Issue by darkfader66669** [blackhole89/notekit#152]
sudo add-apt-repository ppa:gezakovacs/ppa
[sudo] password for owner:           
Cannot add PPA: ''This PPA does not support jammy''.

HELP: can this be solved?
Creating Bootable USB Device Using Unetbootin Tool

To install UNetbootin on Ubuntu and Ubuntu-based Linux distributions, use the following [apt command](https://www.tecmint.com/apt-advanced-package-command-examples-in-ubuntu/) to add PPA and install it.

$ sudo add-apt-repository ppa:gezakovacs/ppa
$ sudo apt-get update
$ sudo apt-get install unetbootin

**Comment by LyesSaadi** [comment]
This looks like spam. Reported it to GitHub.

**Comment by darkfader66669** [comment]
> This looks like spam. Reported it to GitHub.

THANKS BUT IT IS NOT SPAM  IT WAS A LEGIT QUESTION WOW....

**Comment by LyesSaadi** [comment]
Ok, so, pushed by a notekit contributor I looked into this further, and I now have doubts about this being a spam, and just someone lost here :sweat_smile:... For that, I have to present my deepest apologies.

About your question, this is absolutely not the place to ask it, as this is not a public forum for help, but an Open Source development project. You probably landed here by mistake from search engines somehow linking to an issue of this project by searching for the error you got. You probably should ask your question [here](https://launchpad.net/~gezakovacs) (there's an e-mail you can contact the guy with if you create an account, and an "answers" question to ask for help), as we have no relation with the project in question.

The reason I thought this was spam is that this request was so random, and so out of place to ask here, and that it linked to a website which, had minimal links to this project. Some people spam public places like this one with links to other website to boost their ranking in search engines, and I thought this was the case here. But, looking into it further looks like you were genuinely a confused user, and for that I apologize again for my rude comment.
