### ISSUE TITLE
Asking for clearance to creating a Fedora COPR Repo.

### ISSUE THREAD

**Issue by LyesSaadi** [blackhole89/notekit#16]
Hi!

I successfully packaged [NoteKit for Fedora](https://gitlab.com/LyesSaadi/spec/tree/master/notekit), ~~at least for X11 (discovered a bug, will report it later. I'm gathering more information)~~ (EDIT: This was just a random error apparently, it just disappeared ¯\\\_(ツ)\_/¯, so it works well on wayland as well). And I wanted to ask for clearance for launching an automated COPR repo (equivalent of AUR) for fedora that will build nightly or weekly NoteKit.

I also wanted you to review some details about the package, as that's the first time that I do something like that :stuck_out_tongue::
**Summary:** A GTK3 hierarchical markdown notetaking application with tablet support.
**Description:** This program is a structured notetaking application based on GTK+ 3. Write your notes in instantly-formatted Markdown, organise them in a tree of folders that can be instantly navigated from within the program, and add hand-drawn notes by mouse, touchscreen or digitiser.
**Desktop File:**
```
[Desktop Entry]
Version=%{current}
Name=NoteKit
GenericName=NoteKit
Comment=Write your notes in instantly-formatted Markdown
Icon=accessories-text-editor
Exec=notekit
Terminal=false
Type=Application
Categories=Office;
Keywords=note;onenote;notetaking;markdown;
```
Screenshot:
![NoteKit](https://user-images.githubusercontent.com/33597258/64711246-31202180-d4b1-11e9-949f-ac43491e03a7.png)

**Comment by blackhole89** [comment]
I'm totally okay with this, thanks for your effort!

I would be curious to hear more about the failure under Wayland, since @freemin7 also mentioned that it didn't work for him. (I tried in a Weston window inside X11 and it seemed to work fine, but that's probably not representative of a Wayland-from-the-bottom-up stack.) It might well be that some assumptions I make about the device or window pointers don't actually hold up under it.

By the way, under a dark theme like yours, it might be useful to change the colour for the "markdown:invisible" category in sourceview/classic.xml to black. Otherwise, you might experience some minor ugliness when using horizontal lines (`---`).

**Comment by LyesSaadi** [comment]
Yep, I noticed the `---` issue :wink:. But I can't do it from the spec file. (You could change opacity, maybe by #0000 ?)

Also, the Wayland failure was just a "Segmentation fault (core dumped)" error, it got solved by restarting.

I'll set up the COPR repo and as soon as it is ready I close this issue.

But, should I go with a weekly or daily update ?

**Comment by blackhole89** [comment]
Does setting something like `<style name="markdown:invisible"             foreground="#000000"/>` not work? (Unfortunately, the gtksourceview widget that I'm deriving my editor from does not support opacity in highlight rules. I'm not sure if a manually defined styling tag would have its alpha property respected.)

Weekly update is probably less spammy in the long run. I've been spending a lot of time on this in the past few days, but I should return to making sure I can graduate sooner rather than later, so update frequency will go down.

**Comment by LyesSaadi** [comment]
Unfortunately, the spec file, the one that gives instruction to build the package have absolutely no idea what theme the user is using and intervene only when building.

I'll go for weekly update then.

And, the COPR repo is ready and the second build is successful, ready to ship :wink:: https://copr.fedorainfracloud.org/coprs/lyessaadi/notekit/ ! In the description I put the README without the installation/building instruction as that would have been weird...

**Comment by blackhole89** [comment]
Ah, right. I meant you should make that change for yourself locally; still thinking about what the best way to solve the problem in a way that works automatically for everyone is (I'll probably need some facility to detect the system theme and recolour custom-drawn components such as horizontal lines accordingly anyway).

Thanks again for setting this up; let me know if there are any problems that require a fix on my end!

**Comment by LyesSaadi** [comment]
I've configured the automation of the build, so if I didn't mess up, it should be triggered this Friday at midnight UTC.

> Is there some way of controlling from my end what exactly it will build and ship (so I can still confidently introduce breaking/experimental changes somewhere)? Will it always pull from the master branch, or can you configure which one it will use?

I totally forgot to answer these questions :stuck_out_tongue:.

**Is there some way of controlling from my end what exactly it will build and ship?** : No, BUT, Fedora easily allow to downgrade a package, so don't worry, it won't cause any disruption.

**Will it always pull from the master branch, or can you configure which one it will use?** : For now it will only pull from the master branch, but I can configure which one to use :wink:. I recommend to let it pull from the master branch, and as soon as a beta is ready, I will split the repo into two different packages: notekit-stable (or simply notekit) and notekit-weekly. The first one will follow each new tag release and the weekly... Well, will build weekly :stuck_out_tongue:.

**Comment by LyesSaadi** [comment]
https://fedoramagazine.org/4-cool-new-projects-to-try-in-copr-for-october-2019/ :3

**Comment by blackhole89** [comment]
@LyesSaadi How difficult would it be to include a different version of data/stylesheet.css in the Fedora 31 repository? Per #30, it seems like there is some issue with the bundled version of the Bitstream Charter font, so we'd probably need to default to another one (maybe just replace it with `serif`).

**Comment by LyesSaadi** [comment]
Not too difficult in fact :). I'll work on it !

**Comment by LyesSaadi** [comment]
Do you confirm that you want to change "Bitstream Charter" to "serif" ?

**Comment by blackhole89** [comment]
Yes, I think it should be `serif` on the affected system (Fedora 31 only?). Thanks!

**Comment by LyesSaadi** [comment]
I just began the build process (for all fedoras not only 31, as a package update from Fedora could also break everything). I'll test it and I'll tell you if the issue is solved.

**Comment by LyesSaadi** [comment]
It's done and working ;) !
