### ISSUE TITLE
Curves drawn with tablet input seem very "edgy"

### ISSUE THREAD

**Issue by freemin7** [blackhole89/notekit#2]
![edgy](https://user-images.githubusercontent.com/25376460/64533845-9e4a8000-d314-11e9-82a0-10a9570e14a3.png)

The lines are more edgy than i am used to from Xournal.
Sometimes lines are non continuous. This goes away after resize or after drawing a few more lines 

![non_cont](https://user-images.githubusercontent.com/25376460/64534749-50cf1280-d316-11e9-88e4-ac405110f9a8.png)

**Comment by blackhole89** [comment]
Mouse input is currently not particularly optimised for fast strokes. I have three potential solutions in mind (fiddle with Gdk's [event compression settings](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-set-event-compression); interpolate at insertion time when |(dx,dy)| is too high, breaking down line segments; draw stroke segments as Bezier curves rather than lines), each of which could have performance implications. I'll test them and get back to this ticket.

**Comment by freemin7** [comment]
It mostly works, but sometimes it does not.
lsusb of my wacom device embedded in my screen
`Bus 001 Device 002: ID 056a:5157 Wacom Co., Ltd 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x056a Wacom Co., Ltd
  idProduct          0x5157 
  bcdDevice            0.02
  iManufacturer           1 Wacom Co.,Ltd.
  iProduct                2 Pen and multitouch sensor
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x003b
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              400mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              3 Multitouch
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     522
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               2
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              4 Pen
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     492
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
`
I have no idea if that is the right answer but `sudo dnf info gtk+` gives me:
Name         : gtk+
Epoch        : 1
Version      : 1.2.10
Release      : 89.fc29
Architecture : x86_64
Size         : 2.5 M
Quelle       : gtk+-1.2.10-89.fc29.src.rpm
Repository   : @System
Aus Paketque : fedora
Summary      : The GIMP ToolKit
URL          : http://www.gtk.org/
Lizenz       : LGPLv2+
Description  : The gtk+ package contains the GIMP ToolKit (GTK+), a library for
             : creating graphical user interfaces for the X Window System. GTK+
             : was originally written for the GIMP (GNU Image Manipulation
             : Program) image processing program, but is now used by several
             : other programs as well.

I am using Gnome3 + Wayland
I can try again with X-Server if you want

**Comment by freemin7** [comment]
If you need other info please tell me what to write in the command line.
