### ISSUE TITLE
terminate called after throwing an instance of 'Gtk::CssProviderError'

### ISSUE THREAD

**Issue by warren-fisher** [blackhole89/notekit#20]
I built the source successfully using CodeLite, since I am on Solus, and running the compiled source from CodeLite gave me the notekit GUI as expected. However I do not want to open CodeLite every time, so I navigated to the /Debug folder and tried to run the notekit executable by doing ./notekit from the Debug folder. The following error is output into the terminal  

> (process:7133): glibmm-CRITICAL **: 19:23:26.324: Class::register_derived_type(): base_query.type_name is NULL.
== This is notekit, built at Sat Sep 14 16:33:54 2019. ==
Detected paths:
Config: /home/warren/.config/notekit
Active notes path: /home/warren/.local/share/notekit
Default notes path: /home/warren/.local/share/notekit
Resource path: .
terminate called after throwing an instance of 'Gtk::CssProviderError'
Aborted

I have no knowledge in C++ so I'm pretty helpless in debugging this. I then tried chmod +x notekit, however this did not fix my issue. Any help is appreciated.

**Comment by blackhole89** [comment]
There probably should be better error messages for this, but you need to run it from the root folder of the distribution, not `Debug/`: that is, go up one directory and run `./Debug/notekit`.
(When all else fails, i.e. there's nothing in `/usr/share` etc., the CssProvider defaults to trying to load resources from `data/` relative to the working directory.)

**Comment by warren-fisher** [comment]
Thanks. Problem solved.
