### ISSUE TITLE
Icon proposal

### ISSUE THREAD

**Issue by thomaskole** [blackhole89/notekit#25]
![image](https://user-images.githubusercontent.com/29757178/66780418-0f132800-eed1-11e9-9d37-dee2a41075af.png)

I designed a logo to fit within the general modern Gnome design, without blending in too much.
If you're interested, I can render them down and send the files.

**Comment by blackhole89** [comment]
Looks good, thanks for your effort! I'd be very happy to add it, though it might be subject to change in the future (since even the name "notekit" is a bit of a placeholder that only came to be because I started out using webkit for rendering the document view...).

**Comment by thomaskole** [comment]
Ha, I like "notekit'.
Well, here's the logo as it is now, with the source SVG.
It can always be changed later.

[notekit_icon.zip](https://github.com/blackhole89/notekit/files/3774596/notekit_icon.zip)
