### ISSUE TITLE
Feature Request: Allow selecting any folder

### ISSUE THREAD

**Issue by BeatLink** [blackhole89/notekit#27]
It would be really cool if you can open up any folder as the base folder from a menu. then you could have different folders for different projects. Would that be possible?

**Comment by freemin7** [comment]
I had the same request. It should be possible.
My work around is to create links in the notekit from into the folder i want to use.

**Comment by blackhole89** [comment]
You can already set the base folder manually by editing the config file (defaults to `$HOME/.config/notekit/config.json`, but look at the console output at start to confirm the inferred config folder). I've been planning to make a UI for this for a while, but never got around to.

**Comment by BeatLink** [comment]
Ahh okay! I'll monitor this thread then
