### ISSUE TITLE
Renaming File (in Symlinked Directory?) doesn't work correctly

### ISSUE THREAD

**Issue by maweki** [blackhole89/notekit#29]
Hi,

i am on the COPR repository and I have symlinked my `~/.local/share/notekit` from a syncthing directory to sync my notes. This works fine.

When I open notekit and change the name of a note via the left-hand side tree view, the filename gets changed (correct) but the filename at the top center of the editor stays the same (error). If I now close notekit and reopen it, it tries to reopen the file with the old filename which fails.

I don't know whether the symlinked directory is part of the issue.

I have uploaded a video showcasing the issue to https://maweki.de/files/notekit_renaming_issue.webm

**Comment by blackhole89** [comment]
Thanks for the report! Should hopefully be fixed now.
