### ISSUE TITLE
Continous lines sometimes lose a "subline" when replacing text 

### ISSUE THREAD

**Issue by freemin7** [blackhole89/notekit#3]
![brocken_lines](https://user-images.githubusercontent.com/25376460/64536031-a6a4ba00-d318-11e9-803c-435ff29fb03b.png)

I also made a video what is going on https://cloud.tu-ilmenau.de/s/sSx4AojaGB8MGHo

**Comment by freemin7** [comment]
[notesbase.zip](https://github.com/blackhole89/notekit/files/3590799/notesbase.zip)

notebase attached

**Comment by blackhole89** [comment]
This looks like the bounding-box calculations for each drawing are coming out short one pixel vertically. It could be some rounding algorithm that plays out differently on your machine than it does on mine (so a thin line at a fractional Y position, like, say. 10.4, winds up being drawn in the 11th pixel). I imagine the fix should be easy (add 1 to calculated X and Y sizes) of each drawing; I'll look into it in a bit. Thanks for the detailed bug reports!

**Comment by freemin7** [comment]
No problem i suspected such a problem.
