### ISSUE TITLE
Install executable, files and directories in CMakeLists.txt

### ISSUE THREAD

**Issue by DanySpin97** [blackhole89/notekit#34]

**Comment by blackhole89** [comment]
Can you elaborate? Do you mean there is some CMake feature that lets it generate instructions for `make install`, if the appropriate data is provided in CMakeLists.txt?

**Comment by DanySpin97** [comment]
There is the [install](https://cmake.org/cmake/help/latest/command/install.html) macro which provides this feature. [Example](https://github.com/polybar/polybar/blob/master/CMakeLists.txt#L163).

**Comment by blackhole89** [comment]
Should be done now.

**Comment by DanySpin97** [comment]
It works, thanks!

Can you also use [GNUInstallDirs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) as install folders? They are widely used in both user and package manager build to change the default install location.
