### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by fitojb** [blackhole89/notekit#37]
Please provide Gettext localization support. Then I’d be happy to contribute translating this app into Spanish and Catalan!

**Comment by blackhole89** [comment]
Well, right now the only non-user-entered text in the application are the three tooltips on the "text", "pencil" and "eraser" tools, respectively, so I'm not sure it's worth the work to set up a framework like gettext. (I will however keep it in mind to introduce it from the start if I ever add something that increases the amount of text, such as a configuration dialog!)

It would be great if you could translate parts of the README.md, though! (In particular, I imagine the "Usage notes" section would be very useful to provide in the user's native language.)

**Comment by fitojb** [comment]
Sure. Please enable the wiki for me to add the translated content there; IMHO adding translated READMEs to repos is cluttering them. :)

**Comment by blackhole89** [comment]
Okay, I _think_ I enabled the wiki and made it publicly editable. Let me know if it works!

**Comment by fitojb** [comment]
It does. Thanks!
