### ISSUE TITLE
Checkbox is only matched against uppercase "x"

### ISSUE THREAD

**Issue by bloomvdomino** [blackhole89/notekit#41]
NoteKit matches & creates checked checkboxes with an uppercase "x". This breaks a lot of compatibility with other tools (e.g. Nextcloud Notes), where the checkbox is lowercase "x".

As far as I know it's common to use the lowercase "x". Is there any reason the uppercase "x" is used and could it be changed?

**Comment by blackhole89** [comment]
Fixed. Thanks for the report!
