### ISSUE TITLE
Pos1 and End key do nothing

### ISSUE THREAD

**Issue by freemin7** [blackhole89/notekit#5]
Pos1 and End key can not be used to scroll to the respective end of the file.
Page UP and Page DOWN work though.

**Comment by blackhole89** [comment]
Does Pos1 not take you to the beginning of the current line, and End to its end? (and Ctrl+Pos1/End take you to the beginning and end of the file respectively?) (They do for me, and I think that's the standard behaviour for those keys...)

**Comment by freemin7** [comment]
Ah they do nothing if you are drawing.

**Comment by blackhole89** [comment]
Right, drawing doesn't autofocus the text editor widget. (Relevant if you just click-opened a document and start drawing on it right away.) Maybe it should do that...
