### ISSUE TITLE
Feature request: allow resizing

### ISSUE THREAD

**Issue by gcoimbra** [blackhole89/notekit#50]
Currently, I can only resize notekit so much. It would be nice if the user could resize it further.
Is this simple to implement?

**Comment by blackhole89** [comment]
You mean you want to be able to make the window smaller? There shouldn't be an upper limit on how large you can make it. It's currently set to a minimum of 900x600 pixels, but removing this restriction would be fairly trivial.

**Comment by gcoimbra** [comment]
Thanks a lot @blackhole89 , now I can use it half my window!
