### ISSUE TITLE
Automated builds failing

### ISSUE THREAD

**Issue by blackhole89** [blackhole89/notekit#74]
It seems that all automated builds are now failing due to cLaTeXMath depending on parts of std::experimental::filesystem that are not found. I assume this is related to [this commit](https://github.com/NanoMichael/cLaTeXMath/commit/90c192eaa8b6958e1619939f65cb5a65088313a0). How should we fix this? Is this some kind of version mismatch issue that we can fix on this end, or should I just change the build scripts to pull a fixed version of cLaTeXMath that predates that change for now?

(Paging @sp1ritCS)

**Comment by sp1ritCS** [comment]
See https://github.com/NanoMichael/cLaTeXMath/pull/50 - but I don't know how this relates to cmake

**Comment by sp1ritCS** [comment]
Nope, still failing. 
```
/usr/local/include/clatexmath/utils/string_utils.h:84:58: error: no matching function for call to ‘cref(<unresolved overloaded function type>)’
   s.erase(find_if(s.rbegin(), s.rend(), not1(cref(isspace))).base(), s.end());
```
(https://github.com/sp1ritCS/notekit/runs/1548543005?check_suite_focus=true)

this is probably the fault of https://github.com/NanoMichael/cLaTeXMath/commit/7332b189f11cbeee34a3fc3e45e8f3deae317d4f

summon @Xrysnow

**Comment by Xrysnow** [comment]
Replace `cref(isspace)` with `cref<int(int)>(isspace)` should be ok.

**Comment by blackhole89** [comment]
> Edit: if I see this correctly, the linker does not link with stdc++fs

That was my impression too, but isn't it weird that we have to explicitly link it on our end even if only clatexmath uses it? Maybe I need to tweak how the .a file is created... (that would actually strictly be on our end)

I'm starting to think that maybe hardcoding the commit ID of cLaTeXMath to use in the build scripts is the right approach either way. Anything else is too brittle (why should we our build to break because some dependency or API changed on the cLaTeXMath side?).

**Comment by sp1ritCS** [comment]
> why should we our build to break because some dependency or API changed on the cLaTeXMath side?

instead of hardcoding a commit id, we should use the soversion from the shared library, and @NanoMichael should tag the corresponding commit. And instead of linking clatexmath you should use the meson built shared library in cmake too.

Then minor, non breaking changes can be released (security fixes etc.), while a breaking change will have to wait until someone took the time to check (and fix) the code. But I guess this is going again the the direction of the discussion we had in #68 😂
