### ISSUE TITLE
need release version 

### ISSUE THREAD

**Issue by siduck76** [blackhole89/notekit#76]
notekit needs to have a release version ( like version ) so it could be packaged for void linux.

**Comment by sp1ritCS** [comment]
As NoteKit is currently in "Late alpha". That is the reason why it doesn't have an actual release.

The issue of actual versions have been discussed in the past already on different threads. See: https://github.com/blackhole89/notekit/pull/60#issuecomment-731845034

Im currently using %ct.%h as a versioning scheme. But I'm guessing you cant use that on void?

**Comment by blackhole89** [comment]
I'm thinking of formally tagging a commit 0.1 one of these days, once I'm sufficiently convinced (by way of using it for a while) that there are no glaring bugs.

**Comment by blackhole89** [comment]
I've used it for a few days now and haven't encountered any major problems, so I'm tagging the latest commit 0.1. This should almost agree with the Launchpad version 0.1, except for today's addition of a menu bar when running in non-CSD mode.
