### ISSUE TITLE
Multi-Widget page

### ISSUE THREAD

**Issue by sp1ritCS** [blackhole89/notekit#79]
This would probably require a larger refactor and by that make NoteKit more OneNote like. But I think it is required to add features down the like like floating drawings or a page title.

I think the best way to implement this would be to have GtkLayout as the root element of the page, and the add Gsv widgets as child's to it. This would have the added benefit that the Gsv widgets could be only half the screen size making it more readable.

I don't know if GtkLayout supports this, but it might also allow to zoom into the Notes.

I don't know if this fits your workflow, but It obviously makes the "markdown files in filesystem" approach a lot more difficult. A potential idea I had, was to create a folder called `pagetitle.nk/` that contains a `main.md` (the main note) aswell as other notes called `xcoord-ycoord.md`

**Comment by blackhole89** [comment]
I don't think I particularly like the idea; having the markdown document as the topmost data structure is really one of the core design decisions that set this program apart (if I wanted free-floating widgets, wouldn't forking or contributing to Xournal(++) have been a better idea?). There are advantages to always having one page correspond to one standard-format file and having a well-defined notion of "before" and "after" too; for instance, in a "free-floating" setup, you couldn't trivially insert text before something (that includes both drawings and text) without manually determining which drawings and text blocks need to be moved down by how much.

> Zoom into notes

If we at some point migrate to GTK 4, there is GskTransform which should work for everything.

> Page title

If you think there needs to be one that's determined from the document, the natural approach would be to find the first Markdown heading counting from the page start that is not followed by any higher-level (fewer-#) one...

> Floating drawings

I actually have a plan for this that is compatible with my preceding goal of making it easy to move blocks of content around: floating drawings should be anchored to a particular point in the text and positioned relative to it (by default, this will just be whatever point in the text corresponds to the center of the drawing). In the markdown file, they would be represented by another pseudo-image (![](nk:) or the like) at the point where they are anchored.
