### ISSUE TITLE
No way to open another folder as base/root folder

### ISSUE THREAD

**Issue by freemin7** [blackhole89/notekit#8]
Having an option to add folder as root which are not under notekit-*/notesbase would be great. That could be really helpful if you already have an existing folder structure and want to continue using it

1. I could imagine either having a way to change the base folder above the folder tree 
2. I would even better if you could multiple different folders as base in the side bar at the same time

**Comment by blackhole89** [comment]
That's definitively planned. I just need to figure out where to store the config.json file. Ideally, this file would store the location of the root folder, but it's currently _inside_ the root folder.

In the meantime, you can add other locations as subfolders by putting a symlink to them into ./notesbase: e.g. `ln -s ~/mynotes mynotes`.

**Comment by freemin7** [comment]
This feature could be emulated with simlinks as you said but it would be an ugly work around if it worked. I did a 
``` cd notesbase/
ln -s ~ home```
and the link works in the file explorer but not in  notekit
 

Another thought: Maybe you want multiple `config.json` for different work space?

**Comment by blackhole89** [comment]
How exactly does the not working in notekit manifest itself? I just checked, and symlinks below `notesbase/` seem to work without a hitch on my end.

**Comment by freemin7** [comment]
Well the symlinks are not detected in notekit but work with other programs.
Video here: https://cloud.tu-ilmenau.de/s/EqSPGwdREW3tSnx

**Comment by blackhole89** [comment]
Doing more or less the same thing makes the symlink work as a normal folder on my end. I wonder why. Would you be willing to try running a custom build with some additional debug output to see what exactly is happening in the enumeration?

**Comment by freemin7** [comment]
Yes

**Comment by blackhole89** [comment]
Thanks! Could you paste me the console output from the binary
[notekit-debug-folder-contents.tar.gz](https://github.com/blackhole89/notekit/files/3597682/notekit-debug-folder-contents.tar.gz) (run in the root folder of the binary distribution), when `notesbase` contains a valid symlink to a folder? (This should simply dump all files that it sees together with the numeric type that `Gio` reports for them, which would tell me whether it fails to treat symlinked folders as folders.)

**Comment by freemin7** [comment]
It works with this binary

**Comment by blackhole89** [comment]
Well, huh. I guess I know what the problem is, then. I also had the relevant call to `enumerate_children` explicitly pass `FILE_QUERY_INFO_NONE` in the copy I sent you as a random experiment (which is supposed to be the [default value](https://developer.gnome.org/glibmm/stable/classGio_1_1File.html#a68c3afcddc0d4860aa2afb4bf715bb20) according to the documentation), and it turns out that your copy of glibmm does not actually treat it as the default value. I'll commit the fix into the mainline repo; in the meantime, if you're not bothered by the additional console output, you can keep using the above binary.
