### ISSUE TITLE
the windows download link is not working. Is there a valid link ?

### ISSUE THREAD

**Issue by jiewangjs** [blackhole89/notekit#88]

**Comment by sp1ritCS** [comment]
Don't think so, you'll have to compile it youself

**Comment by blackhole89** [comment]
The server I'm hosting it on went down. I'll look into it...

(That being said, that binary was extremely outdated, and I need to try and rebuild it at some point.)

**Comment by blackhole89** [comment]
Server is back up, and we just [updated](http://twilightro.kafuka.org/~blackhole89/files/notekit-20210422.zip) the Windows build. It's not perfect (and the package contains a lot of redundant Gtk+ icons), but should be somewhat usable.
