### ISSUE TITLE
thoughts of a mac os x build? 

### ISSUE THREAD

**Issue by rhaynes74** [blackhole89/notekit#90]
Hi folks, any interest in providing a version compiled on a mac?

**Comment by LyesSaadi** [comment]
GTK should be easier to port to. But significantly harder to build to...

**Comment by blackhole89** [comment]
Well, if anyone with a Mac is interested in looking into it... I don't have any Apple hardware and there unfortunately isn't any Wine equivalent for it that would be good enough to test it from another system. I remember previously superficially looking into it and finding that Homebrew has all the required packages available, so perhaps it would not be too difficult.

**Comment by sp1ritCS** [comment]
I've wrote [Homebrew](https://github.com/Homebrew/homebrew-core/) formulas for cLaTeXMath and NoteKit. With them you should be able to build it yourself.

[clatexmath.rb.gz](https://github.com/blackhole89/notekit/files/6382964/clatexmath.rb.gz)
[notekit.rb.gz](https://github.com/blackhole89/notekit/files/6382965/notekit.rb.gz)

On the question on if we could submit them to [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/), I have no Idea if they allow git sources and even If, we'd at least need to comment on why the patch for llvm is needed. (Or find a solution here, that's better)

![Screenshot of a OSX VM running NoteKit](https://media.discordapp.net/attachments/834808258631696407/836513591829725204/unknown.png)

**Comment by sp1ritCS** [comment]
You should be able to install NoteKit now.

If you have homebrew installed, you can just type `brew install --HEAD sp1ritCS/tap/notekit` and then `ln -s /usr/local/opt/notekit/NoteKit.app /Applications/`

It should be in your application launcher (or whatever it's called) then.

**Comment by rhaynes74** [comment]
Many thanks. - I will give it a try!

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
