### ISSUE TITLE
[Linux] Caret is Obnoxious While Drawing

### ISSUE THREAD

**Issue by Swivelgames** [blackhole89/notekit#98]
I'm not sure if this is true on other platforms, but holy crap is this caret distracting :(

It would be ideal if the caret was hidden unless in Edit Text mode. In any other mode, it would be great if the Caret was invisible.

![image](https://user-images.githubusercontent.com/1456302/119545728-bec0a500-bd58-11eb-8788-dfbf681267a8.png)

**Comment by blackhole89** [comment]
Good call. I think efea172cbceefe07bc2854460afd5d0f717aa35a should fix this.

**Comment by Swivelgames** [comment]
@blackhole89 Beautiful! :+1: Thank you :D
